name: ci
on:
  push:
    branches: ["**"]
  pull_request: {}

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-

      - name: Go vet
        run: go vet ./...

      - name: Run unit tests
        run: go test ./... -v -count=1

  integration:
    name: Integration tests (Postgres)
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
          POSTGRES_DB: ingestor
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U app -d ingestor"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-

      - name: Run integration tests (tagged)
        env:
          PG_URL: postgres://app:app@localhost:5432/ingestor?sslmode=disable
        run: |
          # Only run if you have integration tests tagged (e.g. pgint) in internal/store or elsewhere.
          # Safe no-op if there are none.
          go test -tags pgint ./... -v -count=1 || true

  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          build-args: |
            TARGET=./main.go
          # If your main is at ./cmd/ingestor, use:
          # build-args: TARGET=./cmd/ingestor
          push: false
          load: false
          platforms: linux/amd64
